// Inserir produto
POST http://127.0.0.1:5000/produto
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
    "descricao" : "Acai",
    "unidade" : "Litro",
    "quantidade" : 10,
    "preco_real" : 12.50,
    "preco_dolar": 0.0
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

POST http://127.0.0.1:5000/produto
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "descricao" : "Tucuma",
  "unidade" : "Kg",
  "quantidade" : 30,
  "preco_real" : 17.30,
  "preco_dolar": 0.0
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

POST http://127.0.0.1:5000/produto
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "descricao" : "Tapioca",
  "unidade" : "Kg",
  "quantidade" : 5,
  "preco_real" : 4.70,
  "preco_dolar": 0.0
}
// Utiliza-se obrigatoriamente no início da linha os simbolos: ###
// para separar uma requisção da outra. 
###

//Listar todos os produtos em ordem alfabética
GET http://127.0.0.1:5000/produto 
Content-Type: application/json
###

// Obter usuário pelo ID
//GET http://127.0.0.1:5000/product/{id}
GET http://127.0.0.1:5000/produto/2
Content-Type: application/json
###

// Alterar produto pelo ID
// OBS: obrigado preencher o campo ID
PUT http://127.0.0.1:5000/produto 
Content-Type: application/json
// OBS: É necessário pular uma linha, quando existir um corpo (body) 

{
  "id": 2,
  "descricao" : "Macarrao",
  "unidade" : "Kg",
  "quantidade" : 5,
  "preco_real" : 6.50,
  "preco_dolar": 4
}
###

// Obter produto pelo ID
GET http://localhost:5000/produto/1
Content-Type: application/json
###

// Deletar produto pelo ID
DELETE http://127.0.0.1:5000/produto/1
Content-Type: application/json
###

// Listar todos os produtos em ordem alfabética
GET http://localhost:5000/produto/list
Content-Type: application/json
###

